version: 2

sources:
  - name: src
    database: data
    schema: src
    tables:
      - name: bfs_statatlas
      - name: bfs_swissboundaries_2015
      - name: bfs_swissboundaries_gemeinde
      - name: bfs_swissboundaries_bezirk
      - name: bfs_swissboundaries_kanton
      - name: bfs_swissboundaries_land
      - name: bfe_minergie
      - name: ktzh_gp_bevoelkerung
      - name: ktzh_gp_auslaenderanteil
      - name: ktzh_gp_avg_haushaltsgroesse
      - name: swisstopo_zweitwohnungen
      - name: sss_bevoelkerung_wohnbevoelkerung
      - name: sss_bevoelkerung_geschlecht_zivilstand
      - name: stat_tab_bev_demografisch_bilanz
      - name: stat_tab_bev_zivilstand
      - name: stat_tab_bev_heirat
      - name: stat_tab_bev_scheidung
      - name: stat_tab_bev_altersklasse
      - name: stat_tab_bev_geburtsort
      - name: stat_tab_bev_zuwegzug
  - name: ktzh_gwr
    database: data
    schema: src
    tables:
      - name: ktzh_gwr_apartments
      - name: ktzh_gwr_houses
      - name: ktzh_gwr_entrance
  - name: ktzh_metadata
    database: data
    schema: src
    tables:
      - name: ktzh_ogd_metadata
      - name: ktzh_downloads_dataset

groups:
  - name: staging
    owner:
      name: fbardos
      github: fbardos
  - name: snapshots
    owner:
      name: fbardos
      github: fbardos
  - name: intermediate
    owner:
      name: fbardos
      github: fbardos
  - name: marts
    owner:
      name: fbardos
      github: fbardos
  - name: seeds
    owner:
      name: fbardos
      github: fbardos
