x-default-group: &default-group staging

x-tests-stgn-table-gp: &tests-stgn-table-gp
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns: ['bfs_nr', 'indikator_id', 'indikator_jahr']


models:

  # ---------------------------------------------------------------------------
  - name: stgn_bfs_statatlas
  # ---------------------------------------------------------------------------
    config:
      group: *default-group
    tests:
      - dbt_utils.unique_combination_of_columns:  # TEST Surrogate key
          combination_of_columns: ['map_id', 'geo_id', 'variable', 'period_ref', 'geom_code', 'mother_path']
      - dbt_utils.unique_combination_of_columns:  # TEST Strict PK
          combination_of_columns: ['mother_path', 'map_id', 'geo_id', 'variable']

  # ---------------------------------------------------------------------------
  - name: stgn_ktzh_gp_bevoelkerung
  # ---------------------------------------------------------------------------
    config:
      group: *default-group
    tests:
      - <<: *tests-stgn-table-gp

  # ---------------------------------------------------------------------------
  - name: stgn_ktzh_gp_avg_haushaltsgroesse
  # ---------------------------------------------------------------------------
    config:
      group: *default-group
    tests:
      - <<: *tests-stgn-table-gp

  # ---------------------------------------------------------------------------
  - name: stgn_ktzh_gp_auslaenderanteil
  # ---------------------------------------------------------------------------
    config:
      group: *default-group
    tests:
      - <<: *tests-stgn-table-gp



