x-tests-stgn-table-gp: &tests-stgn-table-gp
  - dbt_utils.unique_combination_of_columns:
      combination_of_columns: ['bfs_nr', 'indikator_id', 'indikator_jahr']


models:

  # ---------------------------------------------------------------------------
  - name: stgn_bfs_statatlas
  # ---------------------------------------------------------------------------
    tests:
      - dbt_utils.unique_combination_of_columns:  # TEST Surrogate key
          combination_of_columns: ['map_id', 'geo_id', 'variable', 'period_ref', 'geom_code', 'mother_path']
      - dbt_utils.unique_combination_of_columns:  # TEST Strict PK
          combination_of_columns: ['mother_path', 'map_id', 'geo_id', 'variable']

  # ---------------------------------------------------------------------------
  - name: stgn_swissboundaries_gemeinde
  # ---------------------------------------------------------------------------

  # ---------------------------------------------------------------------------
  - name: stgn_swissboundaries_bezirk
  # ---------------------------------------------------------------------------

  # ---------------------------------------------------------------------------
  - name: stgn_swissboundaries_kanton
  # ---------------------------------------------------------------------------

  # ---------------------------------------------------------------------------
  - name: stgn_swissboundaries_land
  # ---------------------------------------------------------------------------

  # ---------------------------------------------------------------------------
  - name: stgn_ktzh_gp_bevoelkerung
  # ---------------------------------------------------------------------------
    tests:
      - <<: *tests-stgn-table-gp

  # ---------------------------------------------------------------------------
  - name: stgn_ktzh_gp_avg_haushaltsgroesse
  # ---------------------------------------------------------------------------
    tests:
      - <<: *tests-stgn-table-gp

  # ---------------------------------------------------------------------------
  - name: stgn_ktzh_gp_auslaenderanteil
  # ---------------------------------------------------------------------------
    tests:
      - <<: *tests-stgn-table-gp

  # ---------------------------------------------------------------------------
  - name: stgn_bfe_minergie
  # ---------------------------------------------------------------------------
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: ['gemeinde_bfs_id']

  # ---------------------------------------------------------------------------
  - name: stgn_stab_bev_demografisch_bilanz
  # ---------------------------------------------------------------------------
    config:
      odapi:
        grouping_columns:
          - staatsangehorigkeit
          - geschlecht
          - indicator
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: ['_surr_key']

  # ---------------------------------------------------------------------------
  - name: stgn_stab_bev_zivilstand
  # ---------------------------------------------------------------------------
    config:
      odapi:
        grouping_columns:
          - bevtyp
          - geburtsort
          - geschlecht
          - zivilstand
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: ['_surr_key']

  # ---------------------------------------------------------------------------
  - name: stgn_stab_bev_heirat
  # ---------------------------------------------------------------------------
    config:
      odapi:
        grouping_columns:
          - nationalitaet_a
          - nationalitaet_b
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: ['_surr_key']

  # ---------------------------------------------------------------------------
  - name: stgn_stab_bev_scheidung
  # ---------------------------------------------------------------------------
    config:
      odapi:
        grouping_columns:
          - ehedauer
          - nationalitaet_a
          - nationalitaet_b
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: ['_surr_key']

  # ---------------------------------------------------------------------------
  - name: stgn_stab_bev_altersklasse
  # ---------------------------------------------------------------------------
    config:
      odapi:
        grouping_columns:
          - bevtyp
          - geschlecht
          - zivilstand
          - altersklasse
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: ['_surr_key']

  # ---------------------------------------------------------------------------
  - name: stgn_stab_bev_geburtsort
  # ---------------------------------------------------------------------------
    config:
      odapi:
        grouping_columns:
          - bevtyp
          - geburtsort
          - geschlecht
          - zivilstand
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: ['_surr_key']

  # ---------------------------------------------------------------------------
  - name: stgn_stab_bev_zuwegzug
  # ---------------------------------------------------------------------------
    config:
      odapi:
        grouping_columns:
          - nationalitaet
          - geschlecht
          - migrationstyp
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: ['_surr_key']

  # ---------------------------------------------------------------------------
  - name: stgn_stab_geb_bestand
  # ---------------------------------------------------------------------------
    config:
      odapi:
        grouping_columns:
          - gebkategorie
          - zimmer
          - bauperiode
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: ['_surr_key']

  # ---------------------------------------------------------------------------
  - name: stgn_stab_geb_flaeche
  # ---------------------------------------------------------------------------
    config:
      odapi:
        grouping_columns:
          - gebkategorie
          - flaeche
          - bauperiode
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: ['_surr_key']

  # ---------------------------------------------------------------------------
  - name: stgn_stab_geb_leerwhg
  # ---------------------------------------------------------------------------
    config:
      odapi:
        grouping_columns:
          - wohnraum
          - typ
          - indikator
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: ['_surr_key']

  # ---------------------------------------------------------------------------
  - name: stgn_stab_bau_ausgaben
  # ---------------------------------------------------------------------------
    config:
      odapi:
        grouping_columns:
          - auftraggeber
          - bauwerk
          - arbeit
          - indikator
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: ['_surr_key']

  # ---------------------------------------------------------------------------
  - name: stgn_stab_raum_areal
  # ---------------------------------------------------------------------------
    config:
      odapi:
        grouping_columns:
          - nolc04
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: ['_surr_key']

  # ---------------------------------------------------------------------------
  - name: stgn_stab_raum_noas
  # ---------------------------------------------------------------------------
    config:
      odapi:
        grouping_columns:
          - noas04
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: ['_surr_key']

  # ---------------------------------------------------------------------------
  - name: stgn_stab_arbeit_grenzgaenger
  # ---------------------------------------------------------------------------
    config:
      odapi:
        grouping_columns:
          - geschlecht
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: ['_surr_key']
